version: 2

models:
  - name: dim_customer
    description: "Customer dimension table with Type 2 Slowly Changing Dimensions (SCD) to track historical changes in customer attributes over time."
    columns:
      - name: CUSTOMER_ID
        description: "Unique identifier for each customer. Primary key of the dimension table."
      - name: CUSTOMER_NAME
        description: "Full name of the customer."
      - name: CUSTOMER_EMAIL
        description: "Email address of the customer for communication and marketing purposes."
      - name: CUSTOMER_SINCE_DATE
        description: "Date when the customer first registered or made their first purchase."
      - name: CUSTOMER_END_DATE
        description: "Date when this customer record version became inactive (SCD Type 2)."
      - name: CUSTOMER_STATUS
        description: "Current status of the customer (Active, Inactive, Suspended, etc.)."
      - name: IS_VALID_EMAIL
        description: "Boolean flag indicating whether the email address format is valid."
      - name: VALID_FROM
        description: "Start date for when this version of customer attributes became effective (SCD Type 2)."
      - name: VALID_TO
        description: "End date for when this version of customer attributes is no longer effective (SCD Type 2). Defaults to 9999-12-31 for current records."
      - name: IS_CURRENT
        description: "Boolean flag indicating whether this is the current version of the customer record."

  - name: dim_date
    description: "Date dimension table with comprehensive date attributes for time-based analysis. Contains pre-calculated date components, seasons, and business periods."
    columns:
      - name: date_key
        description: "Surrogate key for the date dimension, typically in YYYYMMDD format."
      - name: year
        description: "Calendar year (e.g., 2024)."
      - name: quarter
        description: "Calendar quarter (1-4)."
      - name: month
        description: "Calendar month (1-12)."
      - name: day
        description: "Day of the month (1-31)."
      - name: day_of_week
        description: "Day of the week (1=Sunday, 7=Saturday)."
      - name: day_of_year
        description: "Day of the year (1-366)."
      - name: week_of_year
        description: "Week number within the year (1-53)."
      - name: month_name
        description: "Full name of the month (e.g., January, February)."
      - name: day_name
        description: "Full name of the day (e.g., Monday, Tuesday)."
      - name: day_type
        description: "Classification of day as 'Weekday' or 'Weekend'."
      - name: season
        description: "Season of the year (Winter, Spring, Summer, Fall)."
      - name: year_quarter
        description: "Combined year and quarter identifier (e.g., '2024-Q1')."
      - name: year_month
        description: "Combined year and month identifier (e.g., '2024-01')."

  - name: dim_products
    description: "Product dimension table containing product master data, inventory information, pricing, and lifecycle status."
    columns:
      - name: PRODUCT_ID
        description: "Unique identifier for the product. Primary key of the dimension table."
      - name: PRODUCT_NAME
        description: "Name or description of the product."
      - name: PRODUCT_CATEGORY_ID
        description: "Foreign key to the product category hierarchy."
      - name: CATEGORY_NAME
        description: "Name of the product category."
      - name: SUBCATEGORY
        description: "Subcategory classification within the main category."
      - name: BRAND
        description: "Brand or manufacturer of the product."
      - name: SUPPLIER_ID
        description: "Identifier for the product supplier or vendor."
      - name: COST_PRICE
        description: "Purchase cost of the product from the supplier."
      - name: RETAIL_PRICE
        description: "Selling price of the product to customers."
      - name: MARGIN_PERCENT
        description: "Profit margin percentage calculated as ((Retail Price - Cost Price) / Retail Price) * 100."
      - name: PROFIT_MARGIN
        description: "Absolute profit margin (Retail Price - Cost Price)."
      - name: STOCK_LEVEL
        description: "Current quantity of product available in inventory."
      - name: REORDER_POINT
        description: "Minimum stock level that triggers a reorder recommendation."
      - name: INVENTORY_STATUS
        description: "Current status of inventory (In Stock, Low Stock, Out of Stock)."
      - name: DISCONTINUED
        description: "Boolean flag indicating whether the product has been discontinued."
      - name: LAUNCH_DATE
        description: "Date when the product was first introduced to the market."
      - name: PRODUCT_STATUS
        description: "Business status of the product considering inventory and discontinuation (Available, Low Stock, Out of Stock, Discontinued)."
      - name: DAYS_SINCE_LAUNCH
        description: "Number of days since the product was launched, calculated from current date."

  - name: fact_sales
    description: "Sales fact table containing transactional sales data with financial metrics, profit calculations, and revenue analysis."
    columns:
      - name: ORDER_ID
        description: "Unique identifier for the sales order. Primary key of the fact table."
      - name: CUSTOMER_ID
        description: "Foreign key to the customer dimension, identifying who made the purchase."
      - name: PRODUCT_ID
        description: "Foreign key to the product dimension, identifying what was purchased."
      - name: ORDER_DATE
        description: "Date when the order was placed."
      - name: ORDER_AMOUNT
        description: "Total amount of the sales order in the local currency."
      - name: ORDER_NUMBER
        description: "Degenerate dimension - business order identifier for reporting and tracing."
      - name: sales_amount
        description: "Revenue amount from the sale (same as order_amount)."
      - name: cost_amount
        description: "Calculated cost of goods sold for this order."
      - name: gross_profit
        description: "Gross profit calculated as sales_amount minus cost_amount."
      - name: gross_margin
        description: "Gross margin percentage calculated as gross_profit divided by sales_amount."