{{
    config(
        tags=['staging', 'products', 'categories']
    )
}}

SELECT
    PRODUCT_ID,
    CATEGORY_ID,
    CATEGORY_NAME,
    SUBCATEGORY,
    BRAND,
    SUPPLIER_ID,
    COALESCE(COST_PRICE, 0) AS COST_PRICE,
    COALESCE(RETAIL_PRICE, 0) AS RETAIL_PRICE,
    COALESCE(MARGIN_PERCENT, 0) AS MARGIN_PERCENT,
    COALESCE(STOCK_LEVEL, 0) AS STOCK_LEVEL,
    COALESCE(REORDER_POINT, 0) AS REORDER_POINT,
    COALESCE(DISCONTINUED, FALSE) AS DISCONTINUED,
    LAUNCH_DATE,
    LAST_UPDATED,
    -- Derived fields
    RETAIL_PRICE - COST_PRICE AS PROFIT_MARGIN,
    CASE 
        WHEN STOCK_LEVEL <= REORDER_POINT THEN 'Needs Reorder'
        WHEN STOCK_LEVEL = 0 THEN 'Out of Stock'
        ELSE 'In Stock'
    END AS INVENTORY_STATUS
FROM {{ ref('product_category') }}